# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    sdk: 'macosx'
    configuration: 'Release'

- bash: ln -s /Users/runner/Library/Developer/Xcode/DerivedData/SettingsExporter-* output

- publish: $(System.DefaultWorkingDirectory)/output/Build/Products/Release/SettingsExporter
  artifact: settings-exporter-mac
